Stop using --preload in an attempt to fix a gunicorn[gevent] error
Apparently the gevent worker of gunicorn needs to monkeypatch the Python
standard library, including the ssl module. This needs to be done before these
modules are ever used. However, the application code imports the requests
library, which calls these modules. When using --preload this happens before
the workers are forked, that is, before the gevent monkeypatching.

Here are the warning and error output:

/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py:65:
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may
lead to errors, including RecursionError on Python 3.6. It may also silently
lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See
https://github.com/gevent/gevent/issues/1016 . Modules that had direct
imports (NOT patched):
['urllib3.util (/usr/local/lib/python3.7/site-packages/urllib3/util/__init__.py)',
'urllib3.util.ssl_ (/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py)'].
  monkey.patch_all(subprocess=True)
[2019-09-17 13:44:22 +0000] [10] [ERROR] Exception on /v0/alignment-computation/ [POST]
Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.7/ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 471 more times]
RecursionError: maximum recursion depth exceeded